Reply to inline comments
charignon/greview pull request #81
Opened 2021-10-03 17:11 UTC by wandersoncferreira

@charignon I had put to myself another requirement for working with PR reviews from emacs: be able to respond to comments inline.

This PR adds such functionality with a few caveats:

- Any new comment (other than in top level portion of buffer) that is *immediately* preceded by a previous comment will be treated as a reply
- I could only find a Github API that accepts single reply calls, so it may be slow or get rate limited if you have *X* number of replies. (the value of X is unknown to me)
- This only works if `github-review-view-comments-in-code-lines` is enabled.
- I tried to change as minimal as possible the current data structures used in the code, but I am afraid I cannot feature flag *everything* without a lot of duplication, if you see a way forward I am all ears :)

Give it a try 👍

2021-10-09 20:46 UTC, charignon requested changes
Left a few comments inline to resolve, thanks again for all your work!

2021-10-09 20:47 UTC, charignon commented
Additionally, feel free to squash the two empty commits from the stack by rebasing on top of the current master

2021-10-10 03:30 UTC, wandersoncferreira commented
Thanks @charignon  for your feedbacks!
BTW: All my comments were made from Github Review Diff buffer 🙃  🙃

2021-10-11 10:32 UTC, wandersoncferreira commented
IMO this is good to go, the main change is guarded on feature flag and the other changes in the comment data structure do not introduce much overhead for users.

2021-10-11 18:55 UTC, charignon commented on github-review.el
> +    (deferred:loop
Is it the same as deferred parallel? Could you double check that these happen indeed in parallel?

2021-10-11 18:55 UTC, charignon approved these changes
Approved, left one comment inline for you to address / test before merging @wandersoncferreira

2021-10-11 19:26 UTC, wandersoncferreira commented on github-review.el
> +    (deferred:loop
Sequential :/ I changed the code to use `deferred:parallel` now. 👍

2021-10-11 19:33 UTC, merged

2021-10-17 13:24 UTC, wandersoncferreira commented on github-review.el
> +  (string-prefix-p "~" l))
made days later